CREATE TABLE artist (
	
	card_number VARCHAR(255),
	card_set VARCHAR(255),
	card_name VARCHAR(255),
	card_type VARCHAR(255),
	year VARCHAR(255)

);

LOAD DATA LOCAL INFILE "cards.csv"
INTO TABLE cards
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 0 LINES;
